% This script helps you convert the model file generated by the binary
% (or the Android) version, which is a plain text file into Matlab .m file,
% then you can apply it to your Matlab version.
%
% Yuan-Ching Teng
% Latest updated July 5, 2014

fileAndroid = './modelAndroid';
fileMatlab  = './modelMatlab.mat';


svmTypeStr = {' c_svc', ' nu_svc', ' one_class', ' epsilon_svr', ' nu_svr'};
kernelTypeStr = {' linear', ' polynomial', ' rbf', ' sigmoid', ' precomputed'};


%% output the mat file
% Load the Android file (text)
fin = fopen(fileAndroid, 'rb');
model = struct();
Parameters = zeros(5,1);
%% Set parameters to default
Parameters(1) = 0;
Parameters(2) = 2;
Parameters(3) = 3;
Parameters(4) = 0;
Parameters(5) = 0;
% svm_type
tline = fgets(fin);
[~, svm_type] = strtok(tline);

%     param[1] = svm_type
%     param[2] = kernel_type
%     param[3] = degree % only appears in polynomial kernel
%     param[4] = gamma % in poly and rbf
%     param[5] = coef0 % in poly

% kernel_type
tline = fgets(fin);
[~, kernel_type] = strtok(tline);
kernelId = find(ismember(kernelTypeStr, kernel_type)) - 1;
Parameters(2) = kernelId;
%% the number of lines in the following depends on the kernel type/id
if kernelId == 1 % polynomial
    tline = fgets(fin);
    [~, degree] = strtok(tline);
    Parameters(3) = str2num(degree);
end
if kernelId == 1 || kernelId == 2 % polynomial or rbf
    tline = fgets(fin);
    [~, gamma] = strtok(tline);
    Parameters(4) = str2num(gamma);
end

if kernelId == 1 % polynomial
    tline = fgest(fin);
    [~, coef0] = strtok(tline);
    Parameter(5) = str2num(coef0);
end
% number of class
tline = fgets(fin);
[~, nC] = strtok(tline);
nr_class = str2num(nC);
% number of support vector
tline = fgets(fin);
[~, nSV] = strtok(tline);
totalSV = str2num(nSV);

% rho (list)


tline = fgets(fin);
[~, rho_list] = strtok(tline);
rho_listOrg = regexp(rho_list, ' ' , 'split');
rho_list = [];
for rho_cell = rho_listOrg
    rho_list = [rho_list;str2num(cell2mat(rho_cell))];
end
% % remove the empty cells
% empCell = cellfun(@isempty, rho_listOrg);
% rho_listOrg(empCell) = [];
% rho_list = [];
% for i = 1:length(rho_list)
%     tline = fgets(fin);
%     [~, rho] = strtok(tline);
%     rho = str2num(rho);
%     rho_list = [rho_list;rho];
% end

% label list
tline = fgets(fin);
[~, strLabels] = strtok(tline);
labelCell_list = regexp(strLabels, ' ', 'split');
label_list = [];
for labelCell = labelCell_list
    label_list = [label_list;str2num(cell2mat(labelCell))];
end
Label = label_list;

%% Insert probA and prob if it is probability supportive
% we cannot know that until we get it 

tline = fgets(fin);
[txt, target] = strtok(tline);
isProb = true;
if strcmp(txt, 'probA')
    % probA  
    ProbA = str2num(target);
    % probB
    tline = fgets(fin);
    [~, probB] = strtok(tline);
    ProbB = str2num(probB);
else
    strNsv = target;
    isProb = false;
    
end
    
%%
% nr_sv
if isProb, tline = fgets(fin);end
[~, strNsv] = strtok(tline);
nSvCell_list = regexp(strNsv, ' ', 'split');
nSv_list = [];
for nSvCell = nSvCell_list
    nSv_list = [nSv_list;str2num(cell2mat(nSvCell))];
end
nSV = nSv_list;

% support vectors row by row
% get the original data first
tline = fgets(fin); % skip the identifier "SV"
tline = fgets(fin);
SVorigin = {};
while ischar(tline)
    SVorigin = [SVorigin;tline];
    tline = fgets(fin);
end

% check the matrix dimension
maxIdx = 1;
for i = 1:length(SVorigin)
    SVrow = SVorigin{i};
    item_list = regexp(SVrow, ' ', 'split');
    lastItem = item_list{size(item_list,2)-1};
    [idx, ~] = strtok(lastItem, ':');
    idx = str2num(idx);
    if idx > maxIdx
        maxIdx = idx;
    end
end

%% get sv_coef (the first nClass -1 columns) and SVs (the rest)
sv_coef = zeros(length(SVorigin),nr_class-1);
SVs = zeros(length(SVorigin), maxIdx);
for row = 1:length(SVorigin)
    SVrow = SVorigin{row};
    item_list = regexp(SVrow, ' ', 'split');
    % SV coef
    for c = 1:nr_class-1
        sv_coef(row, c) = str2double(cell2mat(item_list(c))); 
    end
    % SVs
    for j = nr_class:length(item_list)
        item = item_list(j); % idx:value
        [col, value] = strtok(item, ':');
        col = str2num(cell2mat(col));
        value = cell2mat(value);
        value = str2double(value(2:end));
        SVs(row, col) = value;
    end
end

Parameters(4) = 1/maxIdx;
% write into the model
model.Parameters = Parameters;
model.nr_class = nr_class;
model.totalSV = totalSV;
model.rho = rho_list;
model.Label = Label;
if isProb
model.ProbA = ProbA;
model.ProbB = ProbB;
else
    model.ProbA = [];
    model.ProbB = [];
end
model.nSV = nSV;
model.sv_coef = sv_coef;
model.SVs = sparse(SVs);


fclose(fin);
% output
save(fileMatlab, 'model');




